# Write your MySQL query statement below
SELECT S.CUSTOMER_ID,COUNT(*) AS COUNT_NO_TRANS
FROM VISITS S
LEFT JOIN TRANSACTIONS T 
ON S.VISIT_ID=T.VISIT_ID
WHERE T.VISIT_ID IS NULL
GROUP BY 
CUSTOMER_ID
